import os
from . import jt_logger, format_set
from brancharchitect.logger.html_content import DEBUG_PAGE_CSS
from typing import Optional
from brancharchitect.tree import Node


def generate_debug_html(title: str = "Branch Architect Debug Output") -> str:
    """Generate HTML content for debug output."""
    # Get the actual debug content and any accumulated CSS from the logger
    debug_content = jt_logger.get_html_content()
    logger_css = jt_logger.get_css_content()
    if not debug_content:
        debug_content = "<p>No debug information recorded.</p>"


    # Create HTML structure
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>{DEBUG_PAGE_CSS}\n{logger_css}</style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{title}</h1>
        </header>
        <main>
            {debug_content}
        </main>
        <footer>
            <p style="margin-top: 2em; text-align: center; color: #666;">
                Generated by Branch Architect
            </p>
        </footer>
    </div>
</body>
</html>"""

    return html_content


def write_debug_output(
    html_content: Optional[str] = None,
    output_path: Optional[str] = None,
    title: str = "Branch Architect Debug Output",
) -> Optional[str]:
    """Write HTML debug output to a file."""
    try:
        # Generate HTML only once
        if html_content is None:
            html_content = generate_debug_html(title)

        # Set default output path if needed
        if output_path is None:
            output_dir = os.path.join(
                os.path.dirname(
                    os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
                ),
                "output",
                "debug",
            )
            os.makedirs(output_dir, exist_ok=True)
            output_path = os.path.join(output_dir, "debug_output.html")

        # Write file
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        return output_path

    except Exception as e:
        print(f"Error writing debug output: {str(e)}")
        return None


def log_tree_splits(
    tree1: Node, tree2: Node, title: str = "Tree Split Comparison"
) -> None:
    """Log a side-by-side comparison of splits between two trees with detailed diagnostics."""
    jt_logger.section(title)

    # Get splits using the tree's internal order
    splits1 = tree1.to_splits(with_leaves=True)
    splits2 = tree2.to_splits(with_leaves=True)

    # Log the order/mapping with more detail
    order_map = tree1.split_indices.reverse_encoding

    # Create comparison table with correlation between indices and taxa
    table_data = [
        ["Left Indices", "Left Taxa", "Right Indices", "Right Taxa", "Common?"]
    ]

    # Get all splits sorted by size for consistent ordering
    splits1_sorted = sorted(splits1, key=lambda x: (len(x.indices), x.indices))
    splits2_sorted = sorted(splits2, key=lambda x: (len(x.indices), x.indices))

    # Make lists equal length for table
    max_len = max(len(splits1_sorted), len(splits2_sorted))
    splits1_padded = splits1_sorted + [None] * (max_len - len(splits1_sorted))
    splits2_padded = splits2_sorted + [None] * (max_len - len(splits2_sorted))

    # Track potential encoding mismatches
    mismatches = []

    # Create rows with split indices and taxa
    for split1, split2 in zip(splits1_padded, splits2_padded):
        # Check if the taxa match their indices
        if split1 and split2:
            expected_taxa1 = frozenset(order_map[i] for i in split1.indices)
            expected_taxa2 = frozenset(order_map[i] for i in split2.indices)

            if expected_taxa1 != split1.taxa or expected_taxa2 != split2.taxa:
                mismatches.append(
                    {
                        "left_indices": split1.indices,
                        "left_taxa": split1.taxa,
                        "left_expected": expected_taxa1,
                        "right_indices": split2.indices,
                        "right_taxa": split2.taxa,
                        "right_expected": expected_taxa2,
                    }
                )

        is_common = (
            split1
            and split2
            and split1.indices == split2.indices
            and split1.taxa == split2.taxa
        )

        row = [
            format_set(set(split1.indices)) if split1 else "—",
            format_set(set(split1.taxa)) if split1 else "—",
            format_set(set(split2.indices)) if split2 else "—",
            format_set(set(split2.taxa)) if split2 else "—",
            "✓" if is_common else "✗",
        ]
        table_data.append(row)

    # Log the comparison table
    jt_logger.table(
        table_data[1:], headers=table_data[0], title="Split Comparison", tablefmt="grid"
    )

    # Add CSS for new elements
    jt_logger.add_css(
        """
        .tree-analysis {
            margin: 1em 0;
            padding: 1em;
            background: #252525;
            border-radius: 4px;
        }
        .tree-details {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 1em;
        }
        .detail-block {
            padding: 1em;
            background: #2d2d2d;
            border-radius: 4px;
        }
        .mismatch-analysis {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 1em;
            margin-top: 1em;
        }
        .tree-side {
            padding: 1em;
            background: #2d2d2d;
            border-radius: 4px;
        }
    """
    )

    # Log summary info with enhanced statistics
    jt_logger.info("\nSplit Statistics:")
    jt_logger.info(f"Left Tree Splits: {len(splits1)}")
    jt_logger.info(f"Right Tree Splits: {len(splits2)}")
    jt_logger.info(f"Common Splits: {len(splits1 & splits2)}")
    jt_logger.info(f"Mismatches Found: {len(mismatches)}")
