"""Core type definitions for phylogenetic analysis."""

from typing import Literal, NotRequired, TypedDict, Optional


class TreeMetadata(TypedDict):
    """Global metadata for each tree in the complete interpolation sequence."""

    tree_pair_key: Optional[str]
    """Key to lookup the TreePairSolution that generated this tree, or None for original trees.

    Format: "pair_{source_idx}_{target_idx}"
    - "pair_0_1": Interpolation from tree 0 to tree 1
    - "pair_1_2": Interpolation from tree 1 to tree 2
    - None: This is an original tree, not interpolated

    Use: tree_pair_solutions[tree_pair_key] gets the full solution data
    """

    step_in_pair: Optional[int]
    """One-based local frame ordinal within a pair interpolation.

    This is not a semantic phase identifier. Backend frames can be elided when a
    phase has no visible work, so phase meaning must be derived from adjacent
    tree states and split/SPR event ranges.
    """

    source_tree_global_index: Optional[int]
    """Global index of the source tree this interpolated tree comes FROM (None for original trees)."""

    frame_type: NotRequired[Literal["input_tree", "interpolation_frame"]]
    """Whether this frame is an exact processed input tree or generated by interpolation."""

    state_semantics: NotRequired[
        Literal["processed_input_tree", "algorithmic_intermediate"]
    ]
    """Semantic meaning of the tree state represented by this frame."""

    is_observed_input: NotRequired[bool]
    """True only for exact processed input-tree delimiters."""
